//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BaiCuoiKy.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoaiSachServiceSoap", Namespace="http://tempuri.org/")]
    public partial class LoaiSachService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getAllLoaiSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertLoaiSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateLoaiSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteLoaiSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback loadSachByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertDocGiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateDocGiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteDocGiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllDocGiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDocGiaByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback NhapSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChiTietNhapSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback MuonSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChiTietMuonSachOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LoaiSachService() {
            this.Url = global::BaiCuoiKy.Properties.Settings.Default.BaiCuoiKy_localhost_LoaiSachService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getAllLoaiSachCompletedEventHandler getAllLoaiSachCompleted;
        
        /// <remarks/>
        public event insertLoaiSachCompletedEventHandler insertLoaiSachCompleted;
        
        /// <remarks/>
        public event updateLoaiSachCompletedEventHandler updateLoaiSachCompleted;
        
        /// <remarks/>
        public event deleteLoaiSachCompletedEventHandler deleteLoaiSachCompleted;
        
        /// <remarks/>
        public event getAllSachCompletedEventHandler getAllSachCompleted;
        
        /// <remarks/>
        public event insertSachCompletedEventHandler insertSachCompleted;
        
        /// <remarks/>
        public event updateSachCompletedEventHandler updateSachCompleted;
        
        /// <remarks/>
        public event deleteSachCompletedEventHandler deleteSachCompleted;
        
        /// <remarks/>
        public event loadSachByIDCompletedEventHandler loadSachByIDCompleted;
        
        /// <remarks/>
        public event insertDocGiaCompletedEventHandler insertDocGiaCompleted;
        
        /// <remarks/>
        public event updateDocGiaCompletedEventHandler updateDocGiaCompleted;
        
        /// <remarks/>
        public event deleteDocGiaCompletedEventHandler deleteDocGiaCompleted;
        
        /// <remarks/>
        public event getAllDocGiaCompletedEventHandler getAllDocGiaCompleted;
        
        /// <remarks/>
        public event getDocGiaByIDCompletedEventHandler getDocGiaByIDCompleted;
        
        /// <remarks/>
        public event NhapSachCompletedEventHandler NhapSachCompleted;
        
        /// <remarks/>
        public event ChiTietNhapSachCompletedEventHandler ChiTietNhapSachCompleted;
        
        /// <remarks/>
        public event MuonSachCompletedEventHandler MuonSachCompleted;
        
        /// <remarks/>
        public event ChiTietMuonSachCompletedEventHandler ChiTietMuonSachCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllLoaiSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getAllLoaiSach() {
            object[] results = this.Invoke("getAllLoaiSach", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getAllLoaiSachAsync() {
            this.getAllLoaiSachAsync(null);
        }
        
        /// <remarks/>
        public void getAllLoaiSachAsync(object userState) {
            if ((this.getAllLoaiSachOperationCompleted == null)) {
                this.getAllLoaiSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllLoaiSachOperationCompleted);
            }
            this.InvokeAsync("getAllLoaiSach", new object[0], this.getAllLoaiSachOperationCompleted, userState);
        }
        
        private void OngetAllLoaiSachOperationCompleted(object arg) {
            if ((this.getAllLoaiSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllLoaiSachCompleted(this, new getAllLoaiSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertLoaiSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable insertLoaiSach(string maloai, string tenloai) {
            object[] results = this.Invoke("insertLoaiSach", new object[] {
                        maloai,
                        tenloai});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void insertLoaiSachAsync(string maloai, string tenloai) {
            this.insertLoaiSachAsync(maloai, tenloai, null);
        }
        
        /// <remarks/>
        public void insertLoaiSachAsync(string maloai, string tenloai, object userState) {
            if ((this.insertLoaiSachOperationCompleted == null)) {
                this.insertLoaiSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertLoaiSachOperationCompleted);
            }
            this.InvokeAsync("insertLoaiSach", new object[] {
                        maloai,
                        tenloai}, this.insertLoaiSachOperationCompleted, userState);
        }
        
        private void OninsertLoaiSachOperationCompleted(object arg) {
            if ((this.insertLoaiSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertLoaiSachCompleted(this, new insertLoaiSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateLoaiSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable updateLoaiSach(string maloai, string tenloai) {
            object[] results = this.Invoke("updateLoaiSach", new object[] {
                        maloai,
                        tenloai});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void updateLoaiSachAsync(string maloai, string tenloai) {
            this.updateLoaiSachAsync(maloai, tenloai, null);
        }
        
        /// <remarks/>
        public void updateLoaiSachAsync(string maloai, string tenloai, object userState) {
            if ((this.updateLoaiSachOperationCompleted == null)) {
                this.updateLoaiSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateLoaiSachOperationCompleted);
            }
            this.InvokeAsync("updateLoaiSach", new object[] {
                        maloai,
                        tenloai}, this.updateLoaiSachOperationCompleted, userState);
        }
        
        private void OnupdateLoaiSachOperationCompleted(object arg) {
            if ((this.updateLoaiSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateLoaiSachCompleted(this, new updateLoaiSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteLoaiSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable deleteLoaiSach(string maloai) {
            object[] results = this.Invoke("deleteLoaiSach", new object[] {
                        maloai});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void deleteLoaiSachAsync(string maloai) {
            this.deleteLoaiSachAsync(maloai, null);
        }
        
        /// <remarks/>
        public void deleteLoaiSachAsync(string maloai, object userState) {
            if ((this.deleteLoaiSachOperationCompleted == null)) {
                this.deleteLoaiSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteLoaiSachOperationCompleted);
            }
            this.InvokeAsync("deleteLoaiSach", new object[] {
                        maloai}, this.deleteLoaiSachOperationCompleted, userState);
        }
        
        private void OndeleteLoaiSachOperationCompleted(object arg) {
            if ((this.deleteLoaiSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteLoaiSachCompleted(this, new deleteLoaiSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getAllSach() {
            object[] results = this.Invoke("getAllSach", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getAllSachAsync() {
            this.getAllSachAsync(null);
        }
        
        /// <remarks/>
        public void getAllSachAsync(object userState) {
            if ((this.getAllSachOperationCompleted == null)) {
                this.getAllSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllSachOperationCompleted);
            }
            this.InvokeAsync("getAllSach", new object[0], this.getAllSachOperationCompleted, userState);
        }
        
        private void OngetAllSachOperationCompleted(object arg) {
            if ((this.getAllSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllSachCompleted(this, new getAllSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable insertSach(string id, string id_loai, string tensach, int soluong, float dongia, string tinhtrang) {
            object[] results = this.Invoke("insertSach", new object[] {
                        id,
                        id_loai,
                        tensach,
                        soluong,
                        dongia,
                        tinhtrang});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void insertSachAsync(string id, string id_loai, string tensach, int soluong, float dongia, string tinhtrang) {
            this.insertSachAsync(id, id_loai, tensach, soluong, dongia, tinhtrang, null);
        }
        
        /// <remarks/>
        public void insertSachAsync(string id, string id_loai, string tensach, int soluong, float dongia, string tinhtrang, object userState) {
            if ((this.insertSachOperationCompleted == null)) {
                this.insertSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertSachOperationCompleted);
            }
            this.InvokeAsync("insertSach", new object[] {
                        id,
                        id_loai,
                        tensach,
                        soluong,
                        dongia,
                        tinhtrang}, this.insertSachOperationCompleted, userState);
        }
        
        private void OninsertSachOperationCompleted(object arg) {
            if ((this.insertSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertSachCompleted(this, new insertSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable updateSach(string id, string id_loai, string tensach, int soluong, float dongia, string tinhtrang) {
            object[] results = this.Invoke("updateSach", new object[] {
                        id,
                        id_loai,
                        tensach,
                        soluong,
                        dongia,
                        tinhtrang});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void updateSachAsync(string id, string id_loai, string tensach, int soluong, float dongia, string tinhtrang) {
            this.updateSachAsync(id, id_loai, tensach, soluong, dongia, tinhtrang, null);
        }
        
        /// <remarks/>
        public void updateSachAsync(string id, string id_loai, string tensach, int soluong, float dongia, string tinhtrang, object userState) {
            if ((this.updateSachOperationCompleted == null)) {
                this.updateSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateSachOperationCompleted);
            }
            this.InvokeAsync("updateSach", new object[] {
                        id,
                        id_loai,
                        tensach,
                        soluong,
                        dongia,
                        tinhtrang}, this.updateSachOperationCompleted, userState);
        }
        
        private void OnupdateSachOperationCompleted(object arg) {
            if ((this.updateSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateSachCompleted(this, new updateSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable deleteSach(string id) {
            object[] results = this.Invoke("deleteSach", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void deleteSachAsync(string id) {
            this.deleteSachAsync(id, null);
        }
        
        /// <remarks/>
        public void deleteSachAsync(string id, object userState) {
            if ((this.deleteSachOperationCompleted == null)) {
                this.deleteSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteSachOperationCompleted);
            }
            this.InvokeAsync("deleteSach", new object[] {
                        id}, this.deleteSachOperationCompleted, userState);
        }
        
        private void OndeleteSachOperationCompleted(object arg) {
            if ((this.deleteSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteSachCompleted(this, new deleteSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/loadSachByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable loadSachByID(string id) {
            object[] results = this.Invoke("loadSachByID", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void loadSachByIDAsync(string id) {
            this.loadSachByIDAsync(id, null);
        }
        
        /// <remarks/>
        public void loadSachByIDAsync(string id, object userState) {
            if ((this.loadSachByIDOperationCompleted == null)) {
                this.loadSachByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloadSachByIDOperationCompleted);
            }
            this.InvokeAsync("loadSachByID", new object[] {
                        id}, this.loadSachByIDOperationCompleted, userState);
        }
        
        private void OnloadSachByIDOperationCompleted(object arg) {
            if ((this.loadSachByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loadSachByIDCompleted(this, new loadSachByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertDocGia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable insertDocGia(string id, string name, string CMND, string diachi, string sdt) {
            object[] results = this.Invoke("insertDocGia", new object[] {
                        id,
                        name,
                        CMND,
                        diachi,
                        sdt});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void insertDocGiaAsync(string id, string name, string CMND, string diachi, string sdt) {
            this.insertDocGiaAsync(id, name, CMND, diachi, sdt, null);
        }
        
        /// <remarks/>
        public void insertDocGiaAsync(string id, string name, string CMND, string diachi, string sdt, object userState) {
            if ((this.insertDocGiaOperationCompleted == null)) {
                this.insertDocGiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertDocGiaOperationCompleted);
            }
            this.InvokeAsync("insertDocGia", new object[] {
                        id,
                        name,
                        CMND,
                        diachi,
                        sdt}, this.insertDocGiaOperationCompleted, userState);
        }
        
        private void OninsertDocGiaOperationCompleted(object arg) {
            if ((this.insertDocGiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertDocGiaCompleted(this, new insertDocGiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateDocGia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable updateDocGia(string id, string name, string CMND, string diachi, string sdt) {
            object[] results = this.Invoke("updateDocGia", new object[] {
                        id,
                        name,
                        CMND,
                        diachi,
                        sdt});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void updateDocGiaAsync(string id, string name, string CMND, string diachi, string sdt) {
            this.updateDocGiaAsync(id, name, CMND, diachi, sdt, null);
        }
        
        /// <remarks/>
        public void updateDocGiaAsync(string id, string name, string CMND, string diachi, string sdt, object userState) {
            if ((this.updateDocGiaOperationCompleted == null)) {
                this.updateDocGiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateDocGiaOperationCompleted);
            }
            this.InvokeAsync("updateDocGia", new object[] {
                        id,
                        name,
                        CMND,
                        diachi,
                        sdt}, this.updateDocGiaOperationCompleted, userState);
        }
        
        private void OnupdateDocGiaOperationCompleted(object arg) {
            if ((this.updateDocGiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateDocGiaCompleted(this, new updateDocGiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteDocGia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable deleteDocGia(string id) {
            object[] results = this.Invoke("deleteDocGia", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void deleteDocGiaAsync(string id) {
            this.deleteDocGiaAsync(id, null);
        }
        
        /// <remarks/>
        public void deleteDocGiaAsync(string id, object userState) {
            if ((this.deleteDocGiaOperationCompleted == null)) {
                this.deleteDocGiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteDocGiaOperationCompleted);
            }
            this.InvokeAsync("deleteDocGia", new object[] {
                        id}, this.deleteDocGiaOperationCompleted, userState);
        }
        
        private void OndeleteDocGiaOperationCompleted(object arg) {
            if ((this.deleteDocGiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteDocGiaCompleted(this, new deleteDocGiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllDocGia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getAllDocGia() {
            object[] results = this.Invoke("getAllDocGia", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getAllDocGiaAsync() {
            this.getAllDocGiaAsync(null);
        }
        
        /// <remarks/>
        public void getAllDocGiaAsync(object userState) {
            if ((this.getAllDocGiaOperationCompleted == null)) {
                this.getAllDocGiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllDocGiaOperationCompleted);
            }
            this.InvokeAsync("getAllDocGia", new object[0], this.getAllDocGiaOperationCompleted, userState);
        }
        
        private void OngetAllDocGiaOperationCompleted(object arg) {
            if ((this.getAllDocGiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllDocGiaCompleted(this, new getAllDocGiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDocGiaByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getDocGiaByID(string id) {
            object[] results = this.Invoke("getDocGiaByID", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getDocGiaByIDAsync(string id) {
            this.getDocGiaByIDAsync(id, null);
        }
        
        /// <remarks/>
        public void getDocGiaByIDAsync(string id, object userState) {
            if ((this.getDocGiaByIDOperationCompleted == null)) {
                this.getDocGiaByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDocGiaByIDOperationCompleted);
            }
            this.InvokeAsync("getDocGiaByID", new object[] {
                        id}, this.getDocGiaByIDOperationCompleted, userState);
        }
        
        private void OngetDocGiaByIDOperationCompleted(object arg) {
            if ((this.getDocGiaByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDocGiaByIDCompleted(this, new getDocGiaByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NhapSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable NhapSach(string id, System.DateTime ngaynhap, string ghichu) {
            object[] results = this.Invoke("NhapSach", new object[] {
                        id,
                        ngaynhap,
                        ghichu});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void NhapSachAsync(string id, System.DateTime ngaynhap, string ghichu) {
            this.NhapSachAsync(id, ngaynhap, ghichu, null);
        }
        
        /// <remarks/>
        public void NhapSachAsync(string id, System.DateTime ngaynhap, string ghichu, object userState) {
            if ((this.NhapSachOperationCompleted == null)) {
                this.NhapSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNhapSachOperationCompleted);
            }
            this.InvokeAsync("NhapSach", new object[] {
                        id,
                        ngaynhap,
                        ghichu}, this.NhapSachOperationCompleted, userState);
        }
        
        private void OnNhapSachOperationCompleted(object arg) {
            if ((this.NhapSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NhapSachCompleted(this, new NhapSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChiTietNhapSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ChiTietNhapSach(string id, string id_sach, int soluong, float dongia) {
            object[] results = this.Invoke("ChiTietNhapSach", new object[] {
                        id,
                        id_sach,
                        soluong,
                        dongia});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ChiTietNhapSachAsync(string id, string id_sach, int soluong, float dongia) {
            this.ChiTietNhapSachAsync(id, id_sach, soluong, dongia, null);
        }
        
        /// <remarks/>
        public void ChiTietNhapSachAsync(string id, string id_sach, int soluong, float dongia, object userState) {
            if ((this.ChiTietNhapSachOperationCompleted == null)) {
                this.ChiTietNhapSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChiTietNhapSachOperationCompleted);
            }
            this.InvokeAsync("ChiTietNhapSach", new object[] {
                        id,
                        id_sach,
                        soluong,
                        dongia}, this.ChiTietNhapSachOperationCompleted, userState);
        }
        
        private void OnChiTietNhapSachOperationCompleted(object arg) {
            if ((this.ChiTietNhapSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChiTietNhapSachCompleted(this, new ChiTietNhapSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MuonSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MuonSach(string id, System.DateTime ngaymuon, System.DateTime ngaytra, string id_docgia) {
            object[] results = this.Invoke("MuonSach", new object[] {
                        id,
                        ngaymuon,
                        ngaytra,
                        id_docgia});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MuonSachAsync(string id, System.DateTime ngaymuon, System.DateTime ngaytra, string id_docgia) {
            this.MuonSachAsync(id, ngaymuon, ngaytra, id_docgia, null);
        }
        
        /// <remarks/>
        public void MuonSachAsync(string id, System.DateTime ngaymuon, System.DateTime ngaytra, string id_docgia, object userState) {
            if ((this.MuonSachOperationCompleted == null)) {
                this.MuonSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMuonSachOperationCompleted);
            }
            this.InvokeAsync("MuonSach", new object[] {
                        id,
                        ngaymuon,
                        ngaytra,
                        id_docgia}, this.MuonSachOperationCompleted, userState);
        }
        
        private void OnMuonSachOperationCompleted(object arg) {
            if ((this.MuonSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MuonSachCompleted(this, new MuonSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChiTietMuonSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ChiTietMuonSach(string id, string id_sach, int soluong, float giatien) {
            object[] results = this.Invoke("ChiTietMuonSach", new object[] {
                        id,
                        id_sach,
                        soluong,
                        giatien});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ChiTietMuonSachAsync(string id, string id_sach, int soluong, float giatien) {
            this.ChiTietMuonSachAsync(id, id_sach, soluong, giatien, null);
        }
        
        /// <remarks/>
        public void ChiTietMuonSachAsync(string id, string id_sach, int soluong, float giatien, object userState) {
            if ((this.ChiTietMuonSachOperationCompleted == null)) {
                this.ChiTietMuonSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChiTietMuonSachOperationCompleted);
            }
            this.InvokeAsync("ChiTietMuonSach", new object[] {
                        id,
                        id_sach,
                        soluong,
                        giatien}, this.ChiTietMuonSachOperationCompleted, userState);
        }
        
        private void OnChiTietMuonSachOperationCompleted(object arg) {
            if ((this.ChiTietMuonSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChiTietMuonSachCompleted(this, new ChiTietMuonSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getAllLoaiSachCompletedEventHandler(object sender, getAllLoaiSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllLoaiSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllLoaiSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void insertLoaiSachCompletedEventHandler(object sender, insertLoaiSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertLoaiSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertLoaiSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void updateLoaiSachCompletedEventHandler(object sender, updateLoaiSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateLoaiSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateLoaiSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void deleteLoaiSachCompletedEventHandler(object sender, deleteLoaiSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteLoaiSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteLoaiSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getAllSachCompletedEventHandler(object sender, getAllSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void insertSachCompletedEventHandler(object sender, insertSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void updateSachCompletedEventHandler(object sender, updateSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void deleteSachCompletedEventHandler(object sender, deleteSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void loadSachByIDCompletedEventHandler(object sender, loadSachByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loadSachByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loadSachByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void insertDocGiaCompletedEventHandler(object sender, insertDocGiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertDocGiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertDocGiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void updateDocGiaCompletedEventHandler(object sender, updateDocGiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateDocGiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateDocGiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void deleteDocGiaCompletedEventHandler(object sender, deleteDocGiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteDocGiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteDocGiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getAllDocGiaCompletedEventHandler(object sender, getAllDocGiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllDocGiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllDocGiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getDocGiaByIDCompletedEventHandler(object sender, getDocGiaByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDocGiaByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDocGiaByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void NhapSachCompletedEventHandler(object sender, NhapSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NhapSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NhapSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ChiTietNhapSachCompletedEventHandler(object sender, ChiTietNhapSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChiTietNhapSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChiTietNhapSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void MuonSachCompletedEventHandler(object sender, MuonSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MuonSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MuonSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ChiTietMuonSachCompletedEventHandler(object sender, ChiTietMuonSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChiTietMuonSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChiTietMuonSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591